# Generated by Django 4.2.2 on 2025-09-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.RemoveIndex(
            model_name="networknode",
            name="network_nod_node_ty_1af30c_idx",
        ),
        migrations.RemoveIndex(
            model_name="networknode",
            name="network_nod_created_2df2db_idx",
        ),
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="network.product", verbose_name="Продукты"
            ),
        ),
        migrations.AlterModelTable(
            name="contact",
            table=None,
        ),
        migrations.AlterModelTable(
            name="networknode",
            table=None,
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
