# Generated by Django 4.2.2 on 2025-09-28 04:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "model"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                help_text="Город расположения звена сети",
                max_length=100,
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(
                help_text="Страна расположения звена сети",
                max_length=100,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="Уникальный email адрес звена сети",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="house_number",
            field=models.CharField(
                help_text="Номер дома расположения звена сети",
                max_length=10,
                verbose_name="Номер дома",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(
                help_text="Улица расположения звена сети",
                max_length=100,
                verbose_name="Улица",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="contact",
            field=models.OneToOneField(
                help_text="Контактные данные звена сети",
                on_delete=django.db.models.deletion.CASCADE,
                to="network.contact",
                verbose_name="Контактная информация",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Автоматически устанавливается при создании записи",
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Денежная задолженность в рублях с точностью до копеек",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(
                help_text="Официальное название звена сети",
                max_length=100,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("factory", "Завод"),
                    ("retail", "Розничная сеть"),
                    ("entrepreneur", "Индивидуальный предприниматель"),
                ],
                help_text="Тип звена в иерархии сети",
                max_length=20,
                verbose_name="Тип звена",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Продукты электроники, доступные у звена",
                to="network.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Вышестоящее звено в цепочке поставок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                help_text="Модель или артикул продукта",
                max_length=100,
                verbose_name="Модель",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Наименование продукта электроники",
                max_length=100,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                help_text="Дата первого появления продукта на рынке",
                verbose_name="Дата выхода на рынок",
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["node_type"], name="network_nod_node_ty_1af30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["created_at"], name="network_nod_created_2df2db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(
                fields=["supplier"], name="network_nod_supplie_2016c5_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="contact",
            table="network_contacts",
        ),
        migrations.AlterModelTable(
            name="networknode",
            table="network_nodes",
        ),
        migrations.AlterModelTable(
            name="product",
            table="network_products",
        ),
    ]
